# Mongoid Configuration
# =====================
production:
  sessions:
    default:
      database: {{MONGOID_DATABASE}}
      hosts:
        - '{{MONGOID_HOST}}:{{MONGOID_PORT}}'
      username: {{MONGOID_USERNAME}}
      password: {{MONGOID_PASSWORD}}
  options:
    identity_map_enabled: true